kind: LDAPSyncConfig
apiVersion: v1
url: ldap://idm.internal.aws.testdrive.openshift.com
ca: /etc/origin/master/idm_ldap_ca.crt
bindDN: uid=system,cn=sysaccounts,cn=etc,dc=auth,dc=internal,dc=aws,dc=testdrive,dc=openshift,dc=com
bindPassword: bindingpassword
rfc2307:
  groupsQuery:
    baseDN: cn=groups,cn=accounts,dc=auth,dc=internal,dc=aws,dc=testdrive,dc=openshift,dc=com
    derefAliases: never
    filter: '(|(cn=ose-*))'
  groupUIDAttribute: dn
  groupNameAttributes:
  - cn
  groupMembershipAttributes:
  - member
  usersQuery:
    baseDN: cn=users,cn=accounts,dc=auth,dc=internal,dc=aws,dc=testdrive,dc=openshift,dc=com
    derefAliases: never
  userUIDAttribute: dn
  userNameAttributes:
  - uid
