OCP_ROUTING_SUFFIX: "apps.633949907373.aws.testdrive.openshift.com"
NODE_BRICK_DEVICE: "/dev/xvdd"
NODE_BRICK_DEVICE2: "/dev/xvde"
CNS_NAMESPACE: "storage"
CNS_INFRA_NAMESPACE: "infra-storage"
HEKETI_ADMIN_PW: "myS3cr3tpassw0rd"
HEKETI_ADMIN_PW_BASE64: "bXlTM2NyM3RwYXNzdzByZA=="
HEKETI_USER_PW: "mys3rs3cr3tpassw0rd"
CNS_STORAGECLASS: "glusterfs-storage"
CNS_BLOCK_STORAGECLASS: "glusterfs-registry-block"
CNS_INFRA_STORAGECLASS: "glusterfs-registry"
NODE4_EXTERNAL_FQDN: "node04.633949907373.aws.testdrive.openshift.com"
NODE5_EXTERNAL_FQDN: "node05.633949907373.aws.testdrive.openshift.com"
NODE6_EXTERNAL_FQDN: "node06.633949907373.aws.testdrive.openshift.com"
MASTER_INTERNAL_FQDN: "master.internal.aws.testdrive.openshift.com"
INFRA_INTERNAL_FQDN: "infra.internal.aws.testdrive.openshift.com"
NODE1_INTERNAL_FQDN: "node01.internal.aws.testdrive.openshift.com"
NODE2_INTERNAL_FQDN: "node02.internal.aws.testdrive.openshift.com"
NODE3_INTERNAL_FQDN: "node03.internal.aws.testdrive.openshift.com"
NODE4_INTERNAL_FQDN: "node04.internal.aws.testdrive.openshift.com"
NODE5_INTERNAL_FQDN: "node05.internal.aws.testdrive.openshift.com"
NODE6_INTERNAL_FQDN: "node06.internal.aws.testdrive.openshift.com"
IDM_INTERNAL_FQDN: "idm.internal.aws.testdrive.openshift.com"
WEB_CONSOLE_URL: "https://openshift.633949907373.aws.testdrive.openshift.com/console"
SSH_CONSOLE_URL: "http://ssh.633949907373.aws.testdrive.openshift.com:8080/ssh/host/master.internal.aws.testdrive.openshift.com"
API_HEALTH_URL: "https://openshift.633949907373.aws.testdrive.openshift.com/healthz/ready"
